spring.application.name=sistemas

server.port=${SERVER_PORT:8089}

# URL de conexão (Ex: jdbc:mysql://localhost:3306/nome_banco):
spring.datasource.url=${DB_URL:jdbc:mariadb://localhost:3306/gwj2}

# Usuário do banco
spring.datasource.username=${DB_USERNAME:desenvolvedor}

# Senha do banco (Lida via variável de ambiente DB_PASSWORD ou arquivo .env)
spring.datasource.password=${DB_PASSWORD:}

# Driver do banco
spring.datasource.driver-class-name=${DB_DRIVER:com.mysql.cj.jdbc.Driver}

# Prefixo das tabelas do banco de dados
app.database.prefix=${APP_DB_PREFIX:tab_}

# Configuração para identificação dinâmica de entidades nos templates
app.entity.package=${APP_ENTITY_PACKAGE:com.gwj.model.domain}
app.entities.path=${APP_ENTITIES_PATH:com.gwj.model.domain.entities}